# Generated by Django 3.2.9 on 2021-12-05 08:28

from django.db import migrations, models
import fregat.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fregat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('order_no', 'pk'), 'verbose_name': 'Медиа', 'verbose_name_plural': 'Медиа'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('thread_id', 'is_child', 'order_no', 'pk'), 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AlterModelOptions(
            name='priceitem',
            options={'ordering': ('category__order_no', 'order_no', 'pk'), 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='pricelistcategory',
            options={'ordering': ('order_no', 'pk'), 'verbose_name': 'Категория прайслиста', 'verbose_name_plural': 'Категории прайслистов'},
        ),
        migrations.AlterModelOptions(
            name='teaser',
            options={'ordering': ('order_no', '-publish_date', 'pk'), 'verbose_name': 'Тизер', 'verbose_name_plural': 'Тизеры'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_desktop',
            field=models.ImageField(blank=True, help_text='\n            <p>\n                Фото шириной 2420px. Высота может быть разной,\n                рекомендуется 746px.\n            </p>\n            <p>\n                <strong>Очень важно!</strong> Это фото будет размещено на\n                сайте без какой-либо обработки и оптимизации размера,\n                поэтому оно должно быть подготовлено оператором.\n                Рекомендуется использовать прогрессивный jpeg размером не\n                более 200-400kb.\n            </p>\n            <p>\n                Рекомендуется сжать фото с помощью\n                <a href="https://imagecompressor.com/ru/">этого сервиса</a>.\n            </p>\n        ', null=True, upload_to=fregat.utils.get_upload_path_without_name_keeping, verbose_name='Главное изображение (hero) для десктопов'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_mobile',
            field=models.ImageField(blank=True, help_text='\n            <p>Фото шириной 480px.</p>\n            <p>\n                <strong>Очень важно!</strong> Это фото будет размещено на\n                сайте без какой-либо обработки и оптимизации размера,\n                поэтому оно должно быть подготовлено оператором.\n                Рекомендуется использовать прогрессивный jpeg размером не\n                более 100-200kb.\n            </p>\n            <p>\n                Рекомендуется сжать фото с помощью\n                <a href="https://imagecompressor.com/ru/">этого сервиса</a>.\n            </p>\n        ', null=True, upload_to=fregat.utils.get_upload_path_without_name_keeping, verbose_name='Главное изображение (hero) мобильных телефонов'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_tablet',
            field=models.ImageField(blank=True, help_text='\n            <p>Фото шириной 1024px.</p>\n            <p>\n                <strong>Очень важно!</strong> Это фото будет размещено на\n                сайте без какой-либо обработки и оптимизации размера,\n                поэтому оно должно быть подготовлено оператором.\n                Рекомендуется использовать прогрессивный jpeg размером не\n                более 100-300kb.\n            </p>\n            <p>\n                Рекомендуется сжать фото с помощью\n                <a href="https://imagecompressor.com/ru/">этого сервиса</a>.\n            </p>\n        ', null=True, upload_to=fregat.utils.get_upload_path_without_name_keeping, verbose_name='Главное изображение (hero) для планшетов'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Основное содержимое'),
        ),
    ]
